export const TABLE = 'TABLE';
export const TABLE_SUCCESS = 'TABLE_SUCCESS';
export const TABLE_FAIL = 'TABLE_FAIL';
export const TABLE_FILTER = 'TABLE_FILTER';
export const TABLE_FILTER_SUCCESS = 'TABLE_FILTER_SUCCESS';

export const TABLE_CREATE = 'TABLE_CREATE';
export const TABLE_CREATE_SUCCESS = 'TABLE_CREATE_SUCCESS';
export const TABLE_CREATE_FAIL = 'TABLE_CREATE_FAIL';

export const TABLE_UPDATE = 'TABLE_UPDATE';
export const TABLE_UPDATE_SUCCESS = 'TABLE_UPDATE_SUCCESS';
export const TABLE_UPDATE_FAIL = 'TABLE_UPDATE_FAIL';
